[package]
name = "adventofcode2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "1.0.7"
text_io = "0.1.12"
num="0.4.0"
lazy_static="1.4.0"
regex = "1.7.0"